### ISSUE TITLE
database error on production version

### ISSUE THREAD

**Issue by dhirajkarn** [dhirajkarn/blogger#1]
The following line of code is working fine on localhost, but does not work on heroku.

@blogs = Blog.where("DATE_FORMAT(created_at, '%M %Y') = ?", params[:sel_month])

since its mysql specific query, it won't work on heroku which uses pg. The above query should be written using activerecord which will work on both server.

**Comment by manishdas** [comment]
Use this:
`@blogs = Blog.where('extract(year from created_at) = ? and extract(month from created_at) = ?', params[:year], params[:month])`

**Comment by manishdas** [comment]
Try this after looking your input feed:

```
  date = params[:sel_month].split(" ")  # in split one space is there

  month = Date::MONTHNAMES.index(date[0].capitalize)
  year = date[1].to_i

  @blogs = Blog.where('extract(year from created_at) = ? and extract(month from created_at) = ?', year, month])
```

**Comment by dhirajkarn** [comment]
It worked successfully!
